authors:
  DaUltraMarine:
    name: DaUltraMarine
    description: Admin
    avatar: https://avatars.githubusercontent.com/u/10583568
    url: https://github.com/damarine
  Slabserver Staff Team:
    name: Slabserver Staff Team
    description: Admins
    avatar: https://avatars.githubusercontent.com/u/59237524
    url: https://github.com/slabserver
